### ISSUE TITLE
Requested value 'Disabled' was not found

### ISSUE THREAD

**Issue by davidjrh** [microsoft/Partner-Center-DotNet-Samples#103]
# Steps to reproduce
When using the Microsoft.Store.PartnerCenter nuget package latest version (3.0.1), an exception occurs on deserialization when listing the subscriptions. This suddently started to happen today, July 18th, with no code changes on client side. 

## Expected behavior
Obtaining the list of subscriptions with no errors. 

## Actual behavior
An exception is thrown on deserialization, details below: 
![image](https://user-images.githubusercontent.com/489976/179476076-f4934def-d0f3-446c-a924-cd30a165b949.png)

**PLEASE, Make Microsoft.Store.PartnerCenter nuget source code available on a public repo** as commented on #92

**Comment by davidjrh** [comment]
BTW, the problem in this case seems to be that the "Disabled" status is not defined on the nuget package

![image](https://user-images.githubusercontent.com/489976/179477862-480ac728-28cb-47d1-a173-8a1b3d472e01.png)

**Comment by davidjrh** [comment]
Seems that on v3.1.1 this issue is resolved. I'm wondering why nobody from Microsoft is answering the issues posted on this repo, I'm wondering if anybody is even reading them. 

https://docs.microsoft.com/en-us/partner-center/develop/dotnet-release-notes#version-311

**Comment by anumuru** [comment]
Yes, the issue is fixed in version 3.1.1. Please refer to announcement at: [ https://docs.microsoft.com/en-us/partner-center/announcements/2022-july#15] and release notes at [https://docs.microsoft.com/en-us/partner-center/develop/dotnet-release-notes#version-311]

**Comment by davidjrh** [comment]
Cool! Thanks for the confirmation!
