### ISSUE TITLE
AADSTS50011: No reply address is registered for the application. 

### ISSUE THREAD

**Issue by HeinPauwelyn** [Microsoft/Partner-Center-DotNet-Samples#11]
I'm looking at the SDK samples with new changes you made for secure model. In `LoginUserToAad` a popup appears for user credentials. But when I'm done with the sign on, I've this message:

> AADSTS50011: No reply address is registered for the application. 

From the manifest file of the registered app I use `requiredResourceAccess[0].resourceAccess[0].id` as the `ApplicationId`. The application type to native (it's a not scheduled WPF application _my alternative for #7_).

**Comment by isaiahwilliams** [comment]
Hi @HeinPauwelyn , 

Did you configure your Azure AD application as [documented here](https://github.com/Microsoft/Partner-Center-DotNet-Samples/tree/master/sdk#azure-active-directory)?

**Comment by HeinPauwelyn** [comment]
Thanks I've found it.
