### ISSUE TITLE
Support of .Net Core

### ISSUE THREAD

**Issue by Safirion** [microsoft/Partner-Center-DotNet-Samples#12]
Support using the Partner-Center-SDK for applications built in .net core

**Comment by isaiahwilliams** [comment]
Hi @Safirion, 

Thank you for sharing this feedback. I know this is on the roadmap, but right now I do not know when Microsoft will release a version of the Partner Center .NET SDK that targets .NET Standard. I will see if I can find any additional information you on the timing of this enhancement.

**Comment by KlausPeterRiemer** [comment]
Hi @isaiahwilliams,
is there any Update on this or did you found additional information about the timing?

**Comment by isaiahwilliams** [comment]
Hi @KlausPeterRiemer,

Unfortunately I do not have any official update to share. Unofficially I have put together a version of the SDK that targets .NET standard for various projects that I am building. Please note that this version of the SDK is not supported by Microsoft, so you will only be able to get community support in the event of an issue.

https://www.nuget.org/packages/PartnerCenter.DotNet/

Isaiah Williams
________________________________

**Comment by Safirion** [comment]
Hi @isaiahwilliams,

Thank you for your sharing 👍

**Comment by isaiahwilliams** [comment]
You bet, once there is an official version of the .NET SDK that supports .NET Core an update will be posted in Yammer. With this in mind and due to the fact there is a solution I am going to close this issue. Please let us know if you have any concerns or questions.

**Comment by loopjockey** [comment]
Has there been any update on this?

**Comment by christianarg** [comment]
I'll rephrase the question: will this be ever be done? We're half 2020, .NET 5 is almost here and we can't get official Partner Center Sdk for .NET Core? / standard? You also have a dependency with ADAL which is literally deprecated and will stop working in 2022 https://developer.microsoft.com/en-us/graph/blogs/end-of-support-timelines-for-azure-ad-authentication-library-adal-and-azure-ad-graph/
