### ISSUE TITLE
Duplicated "PartnerMpnId" key in App.config

### ISSUE THREAD

**Issue by jlaherran** [microsoft/Partner-Center-DotNet-Samples#25]
# Steps to reproduce

Try to run the sample "GetSuscriptionsByMpnId" or "VerifyPartnerMpnId" having filled "PartnerMpnId" key in App.config 

## Expected behavior

Use the "PartnerMpnId" configured in App.config

## Actual behavior

The application asks you to enter the MPN ID manually

## Diagnostic logs

No logs but have seen the key is duplicated in app.config file

## Environment

Development

**Comment by isaiahwilliams** [comment]
Thank you for the pull request. We greatly appreciate your help with resolving this issue.
