### ISSUE TITLE
SDKSamples: AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'xxxxxxx-xxx-xxx-xxxx-xxxxxxxxxxxx'. 

### ISSUE THREAD

**Issue by cse-dev** [microsoft/Partner-Center-DotNet-Samples#42]
Having an error when trying to run SDKSamples solution. 
See image below.

![CSP Error](https://user-images.githubusercontent.com/47117428/68793748-8ac0db80-061b-11ea-8767-03bd50cde787.JPG)

It works when we try it on PostMan using the consent link.

**Comment by isaiahwilliams** [comment]
@cse-dev this type error occurs when the specified reply URL in the request for an access token does not match what you have configured in Azure AD. Would it be possible for you to share a screenshot of the redirect URI configuration and the snippet of code you are using to request an access token?

**Comment by isaiahwilliams** [comment]
@cse-dev you should be able to resolve this error by following the steps documented [here](https://github.com/microsoft/Partner-Center-DotNet-Samples/blob/master/sdk/README.md#azure-active-directory). Please let us know if you have any further issues.

**Comment by isaiahwilliams** [comment]
The root cause for this issue was a configuration in Azure AD. It was resolved using the steps documented [here](https://github.com/microsoft/Partner-Center-DotNet-Samples/blob/master/sdk/README.md#azure-active-directory).
