### ISSUE TITLE
Redirect URIs with urn: schemes are prohibited

### ISSUE THREAD

**Issue by SalmanMukhtar** [microsoft/Partner-Center-DotNet-Samples#48]
Hi,

My referesh token is expired so i run the keyvault project to get a referesh token and get the following error.

It was ok a couple of months ago. I am not sure whats changed. 

There is no change in the config file or anything. Why i am getting this? How to solve this issue?

AADSTS500119: Redirect URIs with urn: schemes are prohibited. Use a different scheme, or https://login.microsoftonline.com/common/oauth2/nativeclient

**Comment by SalmanMukhtar** [comment]
i get a null on this line

Newtonsoft.Json.Linq.JObject token = await AuthorizationUtilities.GetAADTokenFromRefreshToken(
                "https://login.microsoftonline.com/" + tenantId,
                "https://api.partnercenter.microsoft.com",
                CspApplicationId,
                CspApplicationSecret,
                refreshToken);

**Comment by ysrinivasarao** [comment]
I am also getting the following error while trying to run tje Secure-app-mdeol keyvalut
Parttner-Center-DotNet-Samples/secure-app-model/keyvault/PartnerConsent/

![image](https://user-images.githubusercontent.com/3209568/96176771-cc789700-0efa-11eb-824f-48c685998528.png)

**Comment by andy754351-cpu** [comment]
Hello, i keep running into this issue when i try to sign in but the odd part is that it redirects well when i use a safari browser, all other browser blocks it.

Message: AADSTS500119: Redirect URIs with urn: schemes are prohibited. Use a different scheme

I’ve tried the native client uri aswell and that too does not work.

I’m using prt client id, is there a working redirect uri that goes with it.

I’ve tried all 3 and none worked.

ms-appx-web://Microsoft.Aad.BrokerPlugin/29d9ed98-a469-4536-ade2-f981bc1d605e%20(Standard%20Windows%20Broker%20path)

https://login.microsoftonline.com/common/oauth2/nativeclient

urn:ietf:wg:oauth:2.0:oob%20(Out-of-band%20alternative)
